src/Utils/generics.ts

It was pointing to the old repository

chore: Update fetchLatestBaileysVersion

---

src/Store/make-in-memory-store.ts

I was having some problem with message status update (4 - read).
The remotejid from update was with "device number" inside, and the stored one was normalized, so it could not be found: "got update for non-existent message".
This solved the problem.
Sorry my poor english ;)

In memory store: normalize user when asserting message list to update messages

---

src/Socket/chats.ts

The current query in `onWhatsApp` doesn't work when multiple `jid` args are provided (the request always times out).

fix: onWhatsApp query for multiple jids

---

src/Store/make-in-memory-store.ts

This is important because as we know that the module "@adiwajshing/keyed-db" is optional :/

fix: cannot find module "@adiwajshing/keyed-db"

---

src/Store/make-in-memory-store.ts

The event "contacts.upsert" was not handled!
Properties "name" and "notify" is not being sended in "messaging-history.set" anymore (as i have noticed sometimes).
So, we need to handle "contacts.upsert" that is sent togheter or just before or in the future, to keep the store updated!
And in "messaging-history.set" check if isLatest to handle the deletition.

In Memory Store: contacts.upsert handle

---

package.json

throws error 
node_modules/.pnpm/@whiskeysockets+baileys@6.2.1_a9c255cd4f7c72f8caee0a723a9801d6/node_modules/@whiskeysockets/baileys/lib/Store/make-in-memory-store.d.ts:1:21 - error TS2307: Cannot find module '@adiwajshing/keyed-db' or its corresponding type declarations.
1 import KeyedDB from '@adiwajshing/keyed-db';
if it's not installed

adding @adiwajshing/keyed-db to dependencies

---

src/Utils/messages.ts

This commit is supposed to fix a visual bug on _WA Web_ when the bot replies to someone's message
- the first message has a visual bug
- second message after applying this patch
this commit also removed the following line of code, to reflect on the changes of WhatsApp in recent versions
https://github.com/WhiskeySockets/Baileys/blob/2dad94b1f032d38b0965402dee5c3c39b12fa7f4/src/Utils/messages.ts#L565-L569

fix: visual bug on wa web

---

src/Socket/groups.ts

If the user does not allow to be added directly, it will be possible to get the invite code and create an invitation message for the user to join the group

fix: added invite property

---

src/Socket/messages-recv.ts
src/Types/GroupMetadata.ts

With this modification, it is possible to list the person who added you/bot to the group in groups.upsert, with the author tag. Before if someone added, there was no way to know who added it, only the owner of the group and etc.

Jid of people who added to the group

---

src/Socket/messages-send.ts

When baileys sends a direct message to someone, it sends the message to all devices of the recipient and oneself.
This is achieved by querying the recipient and oneselves devices via `getUSyncDevices` and then sending the message to all linked devices.
Additionally, the message is always sent to oneselves primary device with id 0, because the primary device is not included in the list of devices returned by `getUSyncDevices`.
This is correct for the multi device api however, it does not work for the mobile api.
Currently, when sending a direct message to someone from the mobile api, the message is mirrored and sent back to itself, which leads to decryption issues.
Because libsignal tries to getSession() for oneselves message, which results in the error `Tried to lookup a session using our …

fix: do not send message to self if the device is 0 (mobile)

---

src/Socket/messages-recv.ts

the 'blocklist.set' event also doesn't emit, but I don't think it's needed

Fix: 'blocklist.update' was never emitted

---

src/Defaults/index.ts

`downloadMediaMessage` crashes when trying to download the media from PTV messages (those video circles).
This fixes it by extending the HKDF map to account for PTV messages

fix downloadMediaMessage crash with ptv messages

---

src/Utils/process-message.ts

This PR will allow Baileys to properly parse incoming ciphertext retry message responses
close #132

Fix message retry for incoming "ciphertext" messages

---

src/Socket/socket.ts
src/Utils/validate-connection.ts

fix #481 #228
If we use
```js
browser: ['MyAwesomeApp', 'chrome', '22.5.0']
```
WhatsApp shows the browser's icon in **Linked Devices**

fix: find platform type based on browser second argument

---

src/Utils/messages.ts

Resolved the function that detects the type of message received.
Previously, the function checked if the message ended with "Message" but we need to see if it includes "Message" because of some messages that contain a suffix after "Message"
ex:
```
pollCreationMessageV2
pollCreationMessageV3
viewOnceMessageV2
viewOnceMessageV2Extension
```

fix: fix message content type detection

---

src/Socket/socket.ts

Previously adding lid does not consider current property values of authState.creds.me which would lost on the next socket reconnect. This fix ensure current values are maintained

Retain existing authState.creds.me properties and add lid

---

package.json
yarn.lock

I found a security warning on one of my repositories that uses Baileys. This warning is caused by the protobufjs Prototype Pollution vulnerability. Here's the description:
The version of protobuf.js (aka protobufjs) from 6.10.0 to 7.2.4 allows Prototype Pollution, which is a different vulnerability than CVE-2022-25878. An attacker can use a user-controlled protobuf message to pollute the prototype of Object.prototype by adding and overwriting its data and functions. This vulnerability can be exploited in various ways: (1) by using the function "parse" to parse protobuf messages on the fly, (2) by loading .proto files using "load" or "loadSync" functions, or (3) by providing untrusted input to the functions ReflectionObject.setParsedOption and util.setProperty. It's essential to note that …

chore: update protobufjs for compatibility and potential bug fixes

---

src/Utils/messages.ts

The $ symbol was added to specify the end of the string in regex.
And improved assertiveness in android, where unknown would never be triggered, all id unknown was specified with android (that can't happen).

getDevice has been improved

---

src/Utils/messages.ts

Support for "view once" audio messages was recently added to Whatsapp (~December 2023).
While this audio messages are not rendered in the web version ("You received a view once voice message. For added privacy, you can only open it on your phone."), they are still accessible in the message received as part of `viewOnceMessageV2Extension`.
This was originally requested in #590.

Support for receiving "view once" audio messages

---

src/Socket/groups.ts

This change corrects the retrieval of the total number of participants within the group.

Update size calculation in extractGroupMetadata function

---

src/Utils/messages-media.ts

Hi there. First time Baileys user here.
As per the README file, I followed the instructions and tried to compile the project using yarn, however, I encountered an error when compiling: 
`src/Utils/messages-media.ts:212:106 - error TS2556: A spread argument must either have a tuple type or be passed to a rest parameter.`
Delving deeper into the code, I found out that the audioDecode function actually accepts only one buffer parameter, instead of all parameter values.
Therefore, this fix changes the passing of ...args to pass only the buffer instead.
After fixing that, I was able to compile and use Baileys. Have also tested it by trying to send myself an audio file.
Screenshots of errors and compilation attached.

Fix: Compile error because of untyped spread argument in audioDecode utility function

---

src/Socket/messages-recv.ts

Hey everyone! This fixes the "Message missing in node" error! Please take a look!
Big thanks to my Sponsors, they allow me to to do work like this. Check out my Sponsors page and donate if you can, it means a lot!

Fix message retry mechanisms

---

src/Socket/messages-recv.ts
src/Utils/decode-wa-message.ts

Return missing messages logic back to normal so that we get the "Message absent from Node" message. This is because the ack-method only works 90% of the time and we'd like to have direct access for later acknowledgement. 
If in case the ack did not work (10% chance), as it requires the phone of the one who contacted you to be online, simply send another ack:
I've included the raw node so that you don't have to pain yourself in re-constructing a BinaryNode. Just turn it back from JSON to a proper BinaryNode and it should be OK.
```js
if (msg.messageStubParameters[0] === "Message absent from node") {
// wait if the message comes, otherwise:
await sock sendMessageAck(JSON.parse(msg.messageStubParameters[1], BufferJSON.reviver));
}
```

fix(missing messages): revert to normal

---

src/Socket/messages-recv.ts
src/Store/make-in-memory-store.ts

Beforehand, it would try to set the picture as the baileys' user because of the "from" attribute, but this has been corrected to either use the jid attribute or the hash for non-contacts (not saved)
Some md5 hash comparison occurs and we can find the contact to update
also, prior to this update, the field would've just stayed at "changed" and cached that too, which would've caused a bunch of crashes I guess at "store.fetchImageUrl"
Because of this though, a socket is recommended to be passed into the config

Fix pfp change notification

---

src/Defaults/index.ts
src/Utils/link-preview.ts
src/Utils/messages.ts

This fixes the thumbnail error when submitting a
Google Maps link.

fix: inefficient method of extracting url from text

---

src/Socket/groups.ts
src/Types/GroupMetadata.ts

If the group is part of a community, the linkedParent returns the jid of the community to which the group belongs.

add linkedParent in groupMetadata

---

src/Socket/socket.ts

`xml send` and `xml recv` where never printed to the log files because the `trace()` calls where not using the 
[pino logger method signature](https://getpino.io/#/docs/api?id=logger) correctly (see implementation of the [pino LOG function](https://github.com/pinojs/pino/blob/v7.11.0/lib/tools.js#L41-L63)), so it was impossible to distinguish received  from sent XML nodes in the logs.
With this change you can filter the Baileys output to create a log of received and send XML nodes using [jq](https://jqlang.github.io/jq/), something like this:
```
tail -f baileys.log | jq -r 'select(has("xml")) | if .msg == "recv xml" then "\u001b[32m← RECV\n\u001b[0m\(.xml)\n" elif .msg == "xml send" then "\u001b[31m→ SEND:\n\u001b[0m\(.xml)\n" else "" end'
```

Fix logging of send/recv xml nodes with pino

---

src/Utils/messages.ts

currently, a `viewOnceMessage` cannot quote another message.
this PR fixes this by adding `contextInfo` in to the nested `viewOnceMessage` type.

fix: enable viewOnce messages to quote

---

src/Utils/messages.ts

Sorry, the previous PR had an issue where it was still sent as ptv even though the value was false.

Fix: sending ptv if true

---

package.json

An issue in Axios 0.8.1 to 1.5.1 reveals the confidential XSRF-TOKEN stored in cookies, including it in the X-XSRF-TOKEN HTTP header for every request made to ANY HOST, allowing attackers to view useful information.

Fix: axios vulnerability (analyzing, don't merge)

---

package.json

Sharp uses libwebp to decode WebP images and versions prior to the latest 0.32.6 are vulnerable to the high severity https://github.com/advisories/GHSA-j7hp-h8jx-5ppr
Or implement `sharp.block({ operation: ["VipsForeignLoadWebp"] });` in the code in messages-media.ts

Fix: sharp vulnerability in libwebp dependency (analyzing, don't merge)

---

package.json
src/Utils/signal.ts
yarn.lock

Most of the work in repository.injectE2ESession is CPU intensive, not IO
So Promise.all doesn't really help here,
but blocks even loop if we're using it inside keys.transaction, and it makes it "sync" actually
This way we chunk it in smaller parts and between those parts we can yield to the event loop
It's rare case when you need to E2E sessions for so many users, but it's possible
When you try to send `status@broadcast` to 3K-10K users - it blocks event loop so much, so no keep alive in between.
Ideally, we should never send so much JIDs, but until we do something
Also I think it's a good practice to always give a time for an event loop (because of IO nature of the websockets)

Run repository.injectE2ESession in chunks

---

src/Socket/socket.ts
src/Types/index.ts
src/Utils/generics.ts

Added: Edge, Firefox, Opera and Safari (by default Chrome) with getPlatformId()
Added FreeBSD, OpenBSD and Solaris in PLATFORM_MAP (use with appropriate)
Updated versions of Ubuntu, MacOS, Baileys and Windows
Feat: In requestPairingCode, the default was just chrome, now it is possible to use Edge, Firefox, Opera and more

Feat: others browsers in requestPairingCode()

---

src/WABinary/encode.ts

Speed up encodeBinaryNode in **x100 times** if encoding many items in content
The problem was that when we use `encodeBinaryNode(item, opts, buffer)` in for loop we actually don't use the result, but we DO convert it to `Buffer.from`
Here:
https://github.com/WhiskeySockets/Baileys/blob/f25f83656a7cadbcdaf66b7fea72b9d4b3a72aa0/src/WABinary/encode.ts#L227
I've moved `Buffer.from` to `sendNode` function, so it converts the array to Buffer only when required (at the end), but not in the middle of the inner loop
```
encodeBinaryNode NEW - 1 - 74ms
encodeBinaryNode NEW - 2 - 68ms
encodeBinaryNode NEW - 3 - 88ms
encodeBinaryNode NEW - 4 - 45ms
encodeBinaryNode NEW - 5 - 34ms
encodeBinaryNode NEW - 6 - 33ms
encodeBinaryNode NEW - 7 - 38ms
encodeBinaryNode NEW - 8 - 30ms
encodeBinaryNode NEW - 9 - …
```

Speed up encodeBinaryNode in x100 times if encoding many items in content

---

src/Utils/generics.ts

When using "requestPairingCode", "typeof platformType" is number, which throws an error

fix: invalid children for header "companion_platform_id": 49 (number)

---

src/Socket/messages-recv.ts
src/Socket/socket.ts
src/Utils/crypto.ts
src/Utils/noise-handler.ts
src/WABinary/decode.ts

This PR changes `inflateSync` and `pbkdf2Sync` to `inflate` and `pbkdf` functions with promisify to prevent blocking event loop

refactor: Change Sync Functions to Promises to Prevent Blocking Event Loop

---

src/Socket/messages-recv.ts

In sendRetryRequest use only id (msgId):
https://github.com/WhiskeySockets/Baileys/blob/6af6bffe31030c85e33777437ad1a4c0276c3ba2/src/Socket/messages-recv.ts#L138
But...
In willSendMessageAgain and updateSendMessageAgainCount uses 'key' with message id and participant, not just id:
https://github.com/WhiskeySockets/Baileys/blob/6af6bffe31030c85e33777437ad1a4c0276c3ba2/src/Socket/messages-recv.ts#L520
https://github.com/WhiskeySockets/Baileys/blob/6af6bffe31030c85e33777437ad1a4c0276c3ba2/src/Socket/messages-recv.ts#L521

Fix: retry cache is not storing

---

src/Socket/messages-recv.ts
src/Types/GroupMetadata.ts
src/Utils/process-message.ts

Added stubType GROUP_PARTICIPANT_CHANGE_NUMBER
When a user changed their number, it was not output in group-participants.update, for people who use caching, this is a problem.
```ts
sock.ev.on('group-participants.update', async({ id, participants, action, author }) => {
if (action === 'modify'){
const newNumber = participants[0]
const oldNumber = author
}
})
```

Feat: Modified number action in group-participants.update

---

README.md

There are no `contacts.set` nor `chat.set` events.

Fix: Readme use upsert events

---

src/Socket/messages-send.ts

If there are no users to search for, the query is executed anyway, leaving it 100ms ~ 500ms slower, decreasing performance and consuming unnecessary resources

Fix: getUSyncDevices

---

src/Utils/messages-media.ts

the conversion is only being carried out to check the file size and compare it with the maximum size limit of the upload hosts. However, these hosts are returning `null` in the `maxContentLengthBytes `field, because of this, the code becomes useless and generates a problem of intense RAM usage without need in cases of sending large files.
I modified it to remove the size check (since it will never be checked since the value is null)
and I passed the stream directly to the axios request, so the file will be sent in stream mode, saving RAM

converting stream to buffer when uploading files without apparent need

---

src/Types/Message.ts
src/Utils/messages.ts

WhatsApp uses pollCreationMessageV2 in communities and community announcements.
They use pollCreationMessage for multiple choices and pollCreationMessageV3 for single select (personal, groups, newsletter)

Support poll v2 and v3 sending

---

src/Socket/messages-send.ts
src/Types/Message.ts
src/Utils/messages.ts

We will now remove all references in code and built-in capability to send buttons or Lists. We announced the deprecation a year and a few months ago.
This PR allows you to add custom Nodes to the outgoing <message> as well. Do with that information what you will!

Deprecation of buttons

---

src/Socket/messages-send.ts
src/Types/Message.ts
src/Utils/messages.ts

The PRs who tried this before me, got various success, only on Web though.. (#787, #545)
This PR brings support to all devices

Pin Messages (all platform support)

---

src/Socket/messages-send.ts

There's no metadata for `status@broadcast` basically
fixes #985

fix: do not fetch group metadata for status

---

src/Socket/messages-send.ts

this PR implements the getUSyncDevices and createNodeParticipants functions to baileys socket object, can be called and structured within the scope of the backend code

feat: exporting getUSyncDevices and createNodeParticipants to socket-send api

---

src/Socket/messages-recv.ts

I was running some tests with Baileys and noticed this simple bug. 
They previously fixed the `processProfilePic` function, but when receiving the contact update event, the ID that came was blank. 
By making this simple fix, the event was corrected.
Cited in https://github.com/WhiskeySockets/Baileys/issues/931

fix: Fixed contacts.update when received changed picture event (close #931)

---

src/Socket/messages-recv.ts
src/Types/Call.ts
src/Utils/generics.ts

- When a call is rejected, Baileys fires the `reject` event twice.
- When a call is accepted, Baileys fires both the `accept` and `reject` events, which is incorrect.
- When a call times out, Baileys fires the `reject` event, which is also incorrect
Terminate tag represents that whatsapp web dont have access to this call anymore, or is timed out or caller hung up, isn't rejected

remove duplicated call reject event / add terminate tag

---

src/Types/Events.ts
src/Utils/event-buffer.ts
src/Utils/history.ts
src/Utils/process-message.ts

The common `messaging-history.set` event when you have buffered events in progress is:
```typescript
{
chats: []
contacts: []
messages: []
isLatest?: boolean
}
```
This event is missing `syncType` and `progress`, and the PDO request id if you requested history.
The new event will be:
```typescript
{
chats: []
contacts: []
messages: []
isLatest?: boolean
progress?: number
syncType?: HistorySyncType
peerDataRequestSessionId?: string | null
}
```

fix: messaging-history.set event not emitting syncType and progress / add PDO request id

---

src/Utils/messages.ts

This fixes an issue where trying to remove a temporary file could throw an `EPERM` error (operation not permitted) if the file was already deleted or inaccessible.
The changes:
1. Added a check using `fs.stat` to verify if the file exists before attempting to delete it.
2. Wrapped the file removal in a `try-catch` to handle any errors gracefully and log a warning if something goes wrong.
3. Ensured the `encWriteStream` is properly closed before proceeding with the cleanup.

messages: fix EPERM error by verifying temp file removal when sending images

---

src/Utils/messages.ts

This commit adjusts the ID length check for desktop, fixing the issue where some desktop IDs were incorrectly classified as "unknown."
Baileys stopped identifying if a message was from WA Desktop (Based on my observations last Year).
This adjustment addresses this issue.
**Usage:**
```javascript
import { getDevice } from 'baileys'
console.log(getDevice('3FBBHEUFEUVUF783B839FB8F3')) // Test
```
**Result:**
```bash
desktop
```

feat: add Id support for desktop

---

README.md

This PR fixes a typo in the documentation by correcting the event name from `messaging.history-set` to `messaging-history.set`. This update ensures consistency and accuracy in the event references.
- Updated event reference in `README.md`:
- Changed from `messaging.history-set` to `messaging-history.set` (2 instances).
- `README.md`

fix: typo on doc 'messaging.history-set' -> 'messaging-history.set'.

---

src/Defaults/index.ts

This patch makes url preview to only generate link previews to urls starting with https.

Fix link preview being generated for email addresses

---

Example/example.ts
package.json
src/Socket/chats.ts
src/Socket/messages-recv.ts
src/Socket/messages-send.ts
src/Utils/auth-utils.ts
yarn.lock

Looking to use this and `node-cache` is not being maintained so I built a new one under my current caching project. This is fully maintained with monthly updates.

fix: migrating to @cacheable/node-cache as it is maintained

---

src/Utils/process-message.ts

Currently the event `chats.update` dont receive the last message.

feat: add last message in chat.update event if is real message

---

package.json
src/Utils/noise-handler.ts
typedoc.json
yarn.lock

**Changes:**
1.  **Removed `libphonenumber-js` as it is no longer used in the project.** (It was previously used in an example, but has since been removed.)
2.  **Upgraded TypeScript to the latest version.** (This reduces disk space usage by approximately  20 MiB  in `node_modules` and improves Language Server Protocol (LSP) performance in the IDE.) The `src/Utils/noise-handler.ts` file was updated due to stricter `Buffer` type checking in TypeScript 5.
3.  **Updated TypeDoc to the latest version.** (A dependency of TypeDoc, Shiki, consumes more disk space in older versions.) This upgrade required the removal of the Google Analytics ID from the configuration, but it can be restored using a JavaScript plugin. What are your thoughts on this, @purpshell?
4.  **Moved `audio-decode` to peer …

Upgrade dev package dependencies

---

src/Utils/chat-utils.ts

Added 'await' to callers of 'makeLtHashGenerator.finish' to handle its Promise return after 'lt-hash.ts' was made asynchronous  by replacing old sync hkdf implementation.
Fixes #1286

fix(sync): complete unfinished async implementation

---

src/WABinary/encode.ts

This fix previne an error when you try to send message to yourself.
The only thing i changed is validate the node content early, before process.
The error throwed is:
```
/home/jlucaso/projects/Baileys2/src/WABinary/encode.ts:229
throw new Error('Invalid node: tag cannot be undefined')
^
Error: Invalid node: tag cannot be undefined
at encodeBinaryNodeInner (/home/jlucaso/projects/Baileys2/src/WABinary/encode.ts:229:9)
at encodeBinaryNodeInner (/home/jlucaso/projects/Baileys2/src/WABinary/encode.ts:254:4)
at encodeBinaryNodeInner (/home/jlucaso/projects/Baileys2/src/WABinary/encode.ts:254:4)
at encodeBinaryNode (/home/jlucaso/projects/Baileys2/src/WABinary/encode.ts:11:18)
at sendNode (/home/jlucaso/projects/Baileys2/src/Socket/socket.ts:138:32)
at …
```

fix: failed to send message to self, add checks for empty strings and invalid nodes

---

src/Utils/auth-utils.ts

Not everyone like me wants to log what our keystore is doing

fix: makeCacheableSignalKeyStore logger optional

---

package.json

The WAProto.proto file is not used in production, so we can save about ~135kb ignoring him

chore: ignore pack .proto files in production builds

---

src/WABinary/decode.ts

jid = 0 and 128
lid = 1 and 129
Participants involved in the analysis of the problem. @canove @viniciusgdr 
This commit solves the problem that when the domain type is different from 0 it is also a jid

fix: readAdJid domainType

---

src/Socket/groups.ts
src/Socket/messages-send.ts
src/Types/GroupMetadata.ts

It allows sending message to groups that now have a `addressing_mode` set to `lid`.

fix: send message to LID addressing_mode groups

---

src/Utils/decode-wa-message.ts
src/WABinary/jid-utils.ts

It fix socket hanging (stop receiving events) due to multiple offline pending notifications.
To test:
- Set log level to "info"
- Connect a normal Whatsapp account (not business)
- Send a few messages on the Meta IA chat
- Restart the socket and take a look on `handled 4 offline messages/notifications`. This number will increase for each message you send on the Meta Ia Chat
- Do the same test on this branch, it should have no offline notifications pending anymore.

fix: proper send receipt to Meta Ia

---

src/Socket/socket.ts

This avoid `unhandledRejection` errors due to timeout.
To test it:
- Turn your computer internet off
- Start baileys
- Send a message through baileys
- You will get an "Connection closed" handled error
- A 60 seconds later (defaultQueryTimeoutMs) you will get an unhandled Time out error and the process will die.
- Try the same with this branch, the Timeout error should never show up and the processing should keep running.
Address:
https://github.com/WhiskeySockets/Baileys/issues/1269
https://github.com/WhiskeySockets/Baileys/issues/1136
https://github.com/WhiskeySockets/Baileys/issues/1078
https://github.com/WhiskeySockets/Baileys/issues/573
https://github.com/WhiskeySockets/Baileys/issues/567
https://github.com/WhiskeySockets/Baileys/issues/34
#1363

Fix catch unhandled timeout error

---

src/Socket/groups.ts
src/Types/GroupMetadata.ts

This makes it easier to understand and use addressingMode by explicitly specifying either 'lid' or 'pn'

change string to "lid" | "pn" in addressingMode

---

src/Socket/messages-recv.ts

- Why whenever I receive ack with status 2 (SERVER_ACK) after I send the message, `fromMe` in key is always `false`? not what I expect
- But if I send message and receive ack status 3 (DELIVERY_ACK), `fromMe` is always `true`, which is what I expect
Here is the payload when the status `SERVER_ACK` or `2` is about to be emitted to event `messages.update`. I realized the confusing part is in here, when `attrs.type` is sender (will be translated as SERVER_ACK), the recipient is there, so `fromMe` becomes `false` , but should be `true` right?
- Handle if `attrs.type === 'sender`, then consider `isNodeFromMe`

Consider `isNodeFromMe` for `key.fromMe` when receive message status `SERVER_ACK`

---

src/Socket/chats.ts

**How to Reproduce**
Add @ at start of your whatsapp name, you will get this error: `xml-not-well-formed`. And you cannot reconnect again until you remove the @

fix: connection error when add @ at start of your name

---

src/Socket/chats.ts
src/Utils/messages-media.ts

The updateProfilePicture and generateProfilePicture functions now accept an optional dimensions parameter, allowing custom width and height for profile pictures. This provides more flexibility for image resizing beyond the default 640x640 size.
*Usage:*

[READY FOR MERGE] Add support for custom profile picture dimensions

---

src/Socket/messages-send.ts
src/Utils/messages.ts

fix #675
- `messageContextInfo` contains **message secret**, we need to send it to the device 
- Fix type - `pollCreationMessage` for **multiple** answers, `pollCreationMessageV3` for a **single** answer

[READY FOR MERGE] Show poll on the sender device

---

src/Types/Message.ts
src/Utils/decode-wa-message.ts

Because new properties are not appearing when trying to access `message.key` on `messages.upsert` event.
before:
after: 
Also, I've added a new "isViewOnce" property to message.key, indicating when its a view once message (atm we are "missing" it due to WhatsApp privacy stuff)

fix: add lid sutff to message.key type

---

src/Utils/history.ts

For certain phone numbers or devices, I'm noticing that certain chat attributes such as `archived` were not available during the initial history sync.
Removing these `delete` lines in `history.ts` makes them available for devs to actually know the initial state of these chat attributes when going through the linking process.
I'm not sure why these lines were present in the first place or what side-effects they have, but I've been testing with these lines removed and they are working as expected.
Potentially fixes #1070

fix: preserve chat attributes in history sync processor

---

src/Socket/socket.ts

When the connection restarts for any reason while opening, it may throw an unhandled rejection and crash the process, due to missing ws error handling.
`Error: WebSocket was closed before the connection was established`
The `catch {}` line should catch the error, but it doesn't because we removed the listeners:
- Set a fake proxy on connection settings, so your connection keep "connecting" until timeout
- call `sock.end()` before the timeout
- Without this PR, this will crash your entire process
- After this PR, the process should keep going.
https://github.com/discordjs/discord.js/issues/7964#issuecomment-1135590782
https://github.com/EvolutionAPI/evolution-api/issues/1302

fix: process crash due to socket closed while opening

---

src/Types/Chat.ts
src/Utils/chat-utils.ts

Add the message range to the clear chat action to allow the action to be made without error (you can't clear the chat without this range)

Added message range to the clear chat action

---

package.json

**Fix Windows path issue in `build` script**
**Issue**
The `build` script in `package.json` was written as:
```json
"build": "tsc -P tsconfig.build.json && tsc-esm-fix --tsconfig='tsconfig.build.json' --ext='.js'"
```
This works on Unix-based systems (macOS/Linux) but **breaks on Windows**, throwing an error:
```
Error: ENOENT: no such file or directory, open 'C:\path\to\project\'tsconfig.build.json''
```
> The single quotes `'` are treated **literally** on Windows CMD/PowerShell, resulting in a malformed path (e.g., `'tsconfig.build.json'` instead of `tsconfig.build.json`).
**Fixes**
Updated the script to remove single quotes around the `--tsconfig` and `--ext` arguments:
```json
"build": "tsc -P tsconfig.build.json && tsc-esm-fix --tsconfig=tsconfig.build.json --ext=.js"
```
**Result** …

fix: build scripts for windows

---

src/Socket/messages-recv.ts

Some calls originating via LID are not arriving with the call offer event.
This fix checks whether the call offer event has already occurred; if not, it forces the event to be emitted.

Fix call offer from lid call

---

src/Utils/event-buffer.ts

The `logger.info` makes Baileys' log verbose.
The flush is executed constantly and could be more useful during troubleshooting sessions with log level = debug

feat: event buffer should use logger.debug instead of logger.info

---

src/Utils/generics.ts

The current padding logic in `writeRandomPadMax16` checks the original random byte before applying the mask, which can result in zero padding values that violate the Signal protocol specification and cause message delivery failures.
When a random byte like `0x10`, `0x20`, `0x30`, etc. is generated:
1. Original value is non-zero, so we apply the mask: `0x10 & 0xf = 0x00`
2. This results in zero padding, which violates Signal protocol requirements (padding must be 1-16 bytes)
3. Recipients reject messages with invalid padding, leading to delivery failures
This affects approximately 6.25% of messages (16 out of 256 possible random byte values).
Reorder the operations to mask first, then validate:
- Apply mask to get value in range 0-15
- Add +1
- This ensures padding is always in the valid …

Fix: prevent zero padding in writeRandomPadMax16 causing message delivery failures

---

src/Utils/decode-wa-message.ts

When the cell phone connected to the instance (Baileys) sends a message to a contact (fromMe = true), the senderPn comes as undefined. This fix fixes this problem temporarily.

Update decode-wa-message.ts (peer_recipient_pn)

---

package.json
src/Socket/messages-recv.ts

When a message retry is triggered but the message is not in store (see implementation example), the retry process never stops. It keeps sending retries endlessly and doesn't respect maxRetriesCache.
_Additionally, I made a few more adjustments._
This only happens when message is not  found in the store.
```
private async getMessage(key: proto.IMessageKey) {
const messageId = `${key.remoteJid}@${key.id}`;
if (!messageId) return proto.Message.fromObject({});
const message = await this.messageHistory.get<WAMessage>(messageId);
if (message?.message) {
return proto.Message.fromObject(message.message);
}
logger.debug(
`Message with key ${key.id} not found in memory storage. ${JSON.stringify(key)}`,
);
return proto.Message.fromObject({});
}
```
I could't reproduce this locally. I have a bot that …

fix: message retries loop 

---

src/Signal/Group/queue-job.ts
src/Socket/socket.ts

Addresses a critical stability issue where network timeouts (408 errors) would cause an unhandled promise rejection, crashing the entire Node.js process. It also fixes a related memory leak that occurred due to frequent, uncontrolled restarts.
related to https://github.com/WhiskeySockets/Baileys/issues/1361 and private dm messages of a user that has multiple instances running in the same machine.
The risky of this changes is low.
1.  **Graceful Timeout Handling in `waitForMessage`:**
-   Modified `waitForMessage` in `src/Socket/socket.ts` to include a `try...catch` block.
-   It now specifically catches `Boom: Timed Out` errors, logs a warning, and returns `undefined`. All other errors are still thrown.
-   This prevents a timeout from becoming a fatal unhandled rejection and allows …

fix(socket): Prevent crashes from timeouts and fix memory leak

---

src/Defaults/index.ts
src/Socket/messages-recv.ts
src/Socket/socket.ts

1 - Socket start validation:
Ensures local pre-key storage is properly aligned with the server by verifying that the current pre-key (referenced in `creds`) actually exists in local storage.
Triggers a fresh upload of pre-keys when:
- The server's pre-key count is below the minimum threshold (existing behavior)
- The latest local pre-key referenced in `creds` is missing (new behavior)
2 - Pre-key specific error approach:
Check if the error resulting in CHIPERTEXT was caused by a pre-key. If so, upload 5 new pre-keys to the WhatsApp server to ensure the new pre-keys are recognized in the pool when calling sendRetryRequest, preventing it from retrying with the same pre-key.
Pre-key storage:
1. Delete all your pre-keys from local storage.
2. Restart your socket.
3. Observe that pre-keys are …

fix: sync pre-keys on socket start and add specific pre-key error approach

---

src/Signal/Group/sender-chain-key.ts
src/Signal/Group/sender-key-state.ts
src/Socket/messages-recv.ts

**first fix**
- added extra check to ensure signatureKeyPublic is either a base64 string or a Buffer
- fallback to empty buffer when unexpected object type is received
- prevents ERR_INVALID_ARG_TYPE error in Buffer.from
**second fix**
previously, some sender chain keys were stored or retrieved as plain objects
(e.g. { '0': 85, '1': 100, ... }) instead of Buffers. this caused
"ERR_INVALID_ARG_TYPE" during initial decryption of skmsg group messages.
fix ensures any chain key object is converted to a proper Buffer
before being passed to SenderChainKey.
**little extra detail lol**
before using this PR set your logger level to debug/warn, you'll notice for every group message you receive would have 2 errors caused by unparsed raw objects that weren't usable buffers or Unit8Array, and because …

fix: handle invalid signatureKeyPublic types in sender-key-state AND fix handling chain key objects for skmsg group message decryption

---

README.md
src/Defaults/index.ts
src/Signal/Group/group_cipher.ts
src/Signal/Group/sender-chain-key.ts
src/Signal/Group/sender-key-distribution-message.ts
src/Signal/Group/sender-key-message.ts
src/Signal/Group/sender-key-record.ts
src/Signal/Group/sender-key-state.ts
src/Socket/messages-recv.ts
src/Socket/socket.ts
src/Utils/browser-utils.ts
src/Utils/chat-utils.ts
src/Utils/decode-wa-message.ts
src/Utils/generics.ts
src/Utils/history.ts
src/Utils/messages-media.ts
src/Utils/messages.ts
src/Utils/noise-handler.ts
src/Utils/process-message.ts
src/Utils/proto-utils.ts
src/Utils/validate-connection.ts
src/WABinary/generic-utils.ts
src/__tests__/Utils/generics.test.ts

This PR addresses a significant `TypeError` regression that occurred after optimizing our protobuf asset generation. The removal of `pbjs` conversion utilities meant that `Buffer` and `Uint8Array` data was being deserialized incorrectly as plain objects, causing crashes in cryptographic functions.
This fix introduces a robust, multi-layered solution to ensure data integrity throughout the application.
1.  **Enhanced `BufferJSON.reviver`**: The core of the fix. Our main JSON `reviver` is now smart enough to detect and correctly convert the old, object-like buffer format. This provides backward compatibility for all users loading legacy auth states from files.
2.  **`decodeAndHydrate` Abstraction**: A new type-safe wrapper, `decodeAndHydrate`, has been created to sanitize data coming …

fix: harden Protobuf Deserialization and Refactor Utilities

---

src/Utils/auth-utils.ts

When using a custom implementation of CacheStore on makeCacheableSignalKeyStore, the cache "get" calls not using await.
Just add the "await" fix the problem, without problems with default NodeCache implementation.

fix makeCacheableSignalKeyStore await cache get

---

src/Socket/messages-send.ts

This remove all the wireJid from messages-send and let libsignal.ts handle it, fixing the addressing in binary attrs.

Fix: groups pn messages-send

---

src/Socket/communities.ts
src/Socket/messages-recv.ts

This PR introduces the new sock `communityFetchLinkedGroups` function, designed to fetch all linked groups from a WhatsApp community.
* **New Function:** Adds the `communityFetchLinkedGroups(jid)` function.
* **Flexible Input:** It accepts a `jid` that can belong to either the parent community or any of its subgroups.
* **Output:** Regardless of the input `jid`, the function identifies the parent community and returns the complete list of all associated groups.

Feat: Fetch all groups from a community given a JID
