src/Tests/test.key-store.ts, src/Tests/utils.ts, src/Types/Auth.ts, src/Utils/auth-utils.ts
refactor: store w transaction:  https://github.com/andresayac/Baileys/commit/a8e26c6eb378c8a65def57b010a1bb31d0bc40fa
fix: auth store transactions + tests: https://github.com/andresayac/Baileys/commit/1802da12a4cd929a9f1d23668792011edbcf0a38
=> added latest pending baileys commit

README.md
change package stable version npmjs
=> Update README.md add stable version package

.github/workflows/update-proto.yml, .gitignore, proto-extract/index.js
Based on https://github.com/Yard-Team/Baileys/pull/1
This workflow will update the proto file with latest stable version of WhatsApp
=> Added update proto workflow

src/Utils/messages.ts
=> fix: get poll request from getAggregateVotesInPollMessage in v1 v2 v3

Example/example.ts, README.md, src/Socket/chats.ts, src/Store/make-in-memory-store.ts, src/Store/object-repository.ts, src/Types/Chat.ts, src/Types/Events.ts, src/Types/Label.ts, src/Types/LabelAssociation.ts, src/Utils/chat-utils.ts
Support for labels is added, a PR that @kuzalekon made was used, it was awaiting review in the previous repository before being removed, an update was also added in the README.md where it is explained how to apply the events for the labels as well as the example.ts script was updated.
=> Label support

README.md, src/Socket/groups.ts
* Approve participants
* Reject participants
* Get list request join participants
=> feat: approve,reject, list request join

README.md
There was a typo in `presence.update`
=> Fix presence.update event in the example

src/Utils/chat-utils.ts
This function was causing errors when compiling using tsc. I added the 'number' function to convert the value and fix the compilation issue with tsc.
=> Update chat-utils.ts to tsc build solution

WASignalGroup/group_cipher.js, WASignalGroup/queue_job.js, WASignalGroup/sender_key_record.js
Reference from libsignal-protocol-ee5b8ba.min.js
I have a question, why don't we maintain libsignal-node instead of just Baileys?
=> Add queue in enc/dec group message

Example/example.ts, src/Socket/messages-recv.ts, src/Socket/socket.ts, src/Types/Auth.ts, src/Utils/auth-utils.ts, src/Utils/crypto.ts, src/Utils/event-buffer.ts, src/Utils/generics.ts, src/Utils/validate-connection.ts
https://github.com/WhiskeySockets/Baileys/issues/248
It should be working already
=> Pairing code login for Web API 

src/Store/make-in-memory-store.ts
https://github.com/WhiskeySockets/Baileys/issues/329
=> Fixed predefined label id

src/Utils/messages.ts
=> proposal: detect desktop and fix device identification using message

src/Socket/groups.ts, src/Socket/messages-recv.ts, src/Types/Call.ts
In call, isGroup returned false, even though it was a group, it was improved and group jid was also added
=> fix: In handle call, isGroup was improved and the group jid was added

src/Socket/socket.ts
=> Fix pairing code browser issue

src/Utils/generics.ts
Adding options for Windows operating system in browsers
=> feat: add option for Windows browser

src/Store/make-cache-manager-store.ts
=> fix(cache): Fixed import

src/Utils/decode-wa-message.ts
hotfix message in group, decrypt error.
Tray cath correction because some events require this function.
=> hotfix message in group

src/Defaults/index.ts, src/Utils/link-preview.ts, src/Utils/messages.ts
This reverts commit f5c1affc4d97c00e01cdbff6e2575a18ddf896fc.
=> Revert "fix: inefficient method of extracting url from text (#741)"

src/Types/Message.ts
https://github.com/WhiskeySockets/Baileys/issues/761
=> Fix: Broadcast option is not present in the message options

src/Store/make-in-memory-store.ts
Later we anyway define logger from defaults it there's no logger
=> Make "logger" optional

src/Socket/chats.ts, src/Socket/socket.ts, src/Types/Auth.ts, src/Utils/auth-utils.ts, src/Utils/noise-handler.ts
Routing info tells the socket where to point. Important detection vector and optimizing for faster startups and longer connections, lower latency
=> feat: Add routing info

src/Socket/chats.ts, src/Store/make-in-memory-store.ts
problem when the user deletes the default label, it remains in store but doesn't exist in WA
=> Remove predefinedLabels

src/Socket/chats.ts, src/Socket/messages-recv.ts
if your code in shouldIgnoreJid blocks @s.whatsapp.net jid, you dont receive app state keys
=> fix shouldIgnoreJid not receive app state keys if blocks @s.whatsapp.net jid

src/Socket/messages-recv.ts
=> fix: linter != to !==

src/Socket/chats.ts
=> fix: profilePictureUrl

src/Socket/groups.ts, src/Socket/messages-send.ts, src/Types/Message.ts, src/Utils/messages.ts
Ever added anyone to your group via baileys and got a 403, with an invite code and expiration? This PR will allow you to send them a private invite like native WhatsApp.
This PR also allows to revoke invites if you wanted to.
=> Send groupInviteMessages (private invites) + Revoke v4 Invite

src/Socket/messages-recv.ts
I only added `try {} finaly{ sendMessageAck() }` in handleMessage/handleNotification, this will send ack even that baileys emit an error, and will propague the error normally
=> guarantee baileys always send ack for messages/notifications to avoid break connections

README.md
- Added badges / Improved Design
- Added modern GitHub README syntax
- Added Indexing
- Added missing examples/explains
- Improved Examples / Simplified Code
- More clarity for examples
- Instructions to real use cases
- Lint
=> Update README (Big Changes, Improve Everthing)

package.json, src/Socket/messages-recv.ts, src/Socket/messages-send.ts, src/Socket/socket.ts, src/Utils/chat-utils.ts, src/Utils/crypto.ts, src/Utils/generics.ts, src/Utils/lt-hash.ts, src/Utils/messages-media.ts, src/Utils/noise-handler.ts, yarn.lock
After this PR, bun will not work anymore with this library because lack of support HKDF in crypto, so i will put in draft.
=> refactor: turn hkdf functions to async and remove extra deps

src/Utils/generics.ts
it was wrong chrome version in `companion_platform_id`
(fix by Pedro)
=> fix pairing code not working

src/WAUSync/Protocols/USyncStatusProtocol.ts
it was getting undefined for some users
=> usync: status-protocol being undefined

.github/workflows/pr-comment.yml
Included a PNPM add command alongside npm and yarn in the PR comment workflow to support projects using PNPM for dependency management.
=> Add PNPM install command to PR comment workflow

src/Signal/Group/sender-key-state.ts
=> fix: handle string format for signing keys in SenderKeyState

src/Defaults/index.ts, src/Socket/chats.ts, src/Socket/messages-send.ts, src/Types/Message.ts, src/Utils/messages.ts
creating call link:
```ts
const token = await sock.createCallLink('audio') //or 'video'
//audio
const link = 'https://call.whatsapp.com/voice/' + token
//video
const link = 'https://call.whatsapp.com/video/' + token
```
sending eventMessage example
```ts
//start in one day 
const date = new Date()
date.setDate(date.getDate() + 1)
await sock.sendMessage(jid, { event: { name: 'test', description: 'testest', startDate: date, call: 'audio' } })
```
=> feat: eventMessage sending / call link creation

src/Defaults/index.ts, src/Socket/business.ts, src/Socket/chats.ts, src/Types/Bussines.ts, src/Types/Chat.ts, src/Types/Message.ts, src/Utils/chat-utils.ts, src/Utils/messages-media.ts
- update bussines profile
- add/edit cover photo
- add/edit/remove quick reply
=> feat(business): change profile/cover photo and manage quick replies

src/Signal/Group/sender-chain-key.ts, src/Signal/Group/sender-key-state.ts, src/Socket/messages-recv.ts, src/Socket/messages-send.ts, src/Types/Socket.ts, src/Utils/auth-utils.ts, src/Utils/messages.ts, src/Utils/process-message.ts
This implementation enables asynchronous cache usage and mget operations, significantly improving performance when sending to large groups.
I’ve tested it in combination with Redis and it reliably handles even fully populated groups without any issues.
I kindly request that this be merged.
=> Async + Multi Cache

src/Utils/auth-utils.ts
This PR fixes a critical regression introduced in commit https://github.com/WhiskeySockets/Baileys/commit/1060f44bff99e91cd8ef02b623215e7da8b936cd that caused the E2E test suite to fail by timing out. The root cause was a connection termination initiated by the WhatsApp server after the client failed to respond to a `ping` request in a timely manner.
The regressing commit replaced an `async-mutex` implementation with `p-queue` (configured with `{ concurrency: 1 }`) for handling database read operations in `addTransactionCapability`.
While both `Mutex.runExclusive()` and `PQueue` serialize access to prevent race conditions, their internal scheduling mechanisms differ. The `PQueue` implementation, being a more feature-rich scheduler, introduced enough overhead to create a **head-of-line …
=> Replace PQueue with Mutex to Resolve Concurrency Deadlock

src/Signal/libsignal.ts, src/Signal/lid-mapping.ts, src/Utils/signal.ts, src/WABinary/jid-utils.ts
Fix linting and errors on master (Type 'string' is not assignable to type 'JidServer')
Tested OK for "SessionError: No sessions
=> fix error and linting
